android/build.gradle, android/gradle.properties
=> Revert "[DSD-1461]Added sonar organisation"

ios/Podfile
* This upgrade brings in the ability to use apple cryptokit.
=> Upgrade to iOS 13

package-lock.json, package.json
- Improve IOS to Android transfer speed
- Added retry for discover services on IOS Wallet
- Fix second time connection issue between Android to Android devices
- Handle GCM decryption failure which leads to crash
=> Release 07-02-2023: Improve IOS transfer speed and minor fixes on Android

ios/Podfile.lock, machines/openIdBle/request.ts, package-lock.json, package.json, screens/Profile/ProfileScreen.tsx
**Android & IOS stability Release build
Enhancements as part of this release:**
- IOS duplicate events [#546]
- Implement Android to Android dynamic MTU negotiation with 250ms timeout [#566]
- [Build change] Change to release mode - Move printing VC SHA on Wallet and Verifier side to Info log
- Show Tuvali commit or tag information in logs [#576]
- Handle and show error when MTU size is less than(<) 64 or unknown on iOS Wallet. [#569]
**Defects:**
- [Transfer Report issue] Cross platform: Intermittently sharing is not working [#567, #543]
=> Improve VC Transfer Stability for iOS and Android

.github/ISSUE_TEMPLATE/bug_report.md
This fix contains updated issue templates.
=> Updated issue template with additional description

components/ui/themes/PurpleTheme.ts, screens/QrLogin/MyBindedVcs.tsx
=> fix(#631): Verify Button going behind the screen and Purple theme button being large in multiple places

.github/workflows/android-build-verify.yml, .github/workflows/android-custom-build.yml, .github/workflows/ios-build.yml
**[iOS] https://mosip.atlassian.net/browse/INJI-29**
- Created a pipeline for iOS build creation.
- Github workflow UI for theme, url, testers group, branch.
**[Android] https://mosip.atlassian.net/browse/INJI-31**
- Created a PR trigger for Android build.
=> INJI-29 | 31 iOS build & Android verify Workflow

.github/workflows/ios-build.yml, ios/fastlane/Fastfile
=> Revert "INJI-29 Modified from self-hosted to mac-runner"

.github/workflows/ios-build.yml, ios/fastlane/Fastfile
https://mosip.atlassian.net/browse/INJI-29
- Modified self-hosted runner to github runner
=> INJI-29 Modified runner as mac

.github/workflows/ios-build.yml
App store connect tester groups are added in workflow
=> Added testers group in workflow

android/app/build.gradle
[ Android ]
Given a fix for the windows build error.
=> fix - INJI-120 -  [Android] changed the version name format

.github/workflows/android-build-verify.yml, .github/workflows/android-custom-build.yml, android/fastlane/Fastfile
- Updated the custom build to generate the release build to upload to Github actions
=> Change from debug build to release build

.github/workflows/android-beta-build.yml, .github/workflows/android-internal-build.yml
Added workflows for,
--> Beta build
--> Internal build
to push to play store
=> Added workflows

ios/Podfile, ios/Podfile.lock
more details here: https://github.com/tw-mosip/inji/pull/86
=> feat: evaluate if update of dev-team during pod install can break iOS CI

screens/Home/MyVcs/HistoryTab.tsx, shared/constants.ts
[INJI-262](https://mosip.atlassian.net/browse/INJI-262) - Audit logs for pinned VC
[INJI-262]: https://mosip.atlassian.net/browse/INJI-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [28-08-2023] - Audit logs for pinned VC

screens/Home/IntroSlidersScreen.tsx
Small device view:-
larger device:-
=> fix(INJI-260):app not aligned properly with the smaller display screen

routes/main.ts
**[INJI-270](https://mosip.atlassian.net/browse/INJI-270)** - In the Arabic language few elements are still in English.
[INJI-270]: https://mosip.atlassian.net/browse/INJI-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (INJI-270) - Fixed that in some languages where few elements are still in English

screens/Home/ReceivedVcsTabMachine.typegen.ts, screens/Settings/ReceivedCards.tsx
Revert "chore: disallow expansion of received cards"
This reverts commit 038b6e42591aa65d6c5fbadd70c6ebe7a3dfa4ba.
=> fix(INJI-286): expand received card popup on click

components/KebabPopUp.tsx, components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts
**[INJI-268](https://mosip.atlassian.net/browse/INJI-268)** - Page headers are not aligned properly 
[INJI-268]: https://mosip.atlassian.net/browse/INJI-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(INJI-268): Adjusted alignment of page headers properly

components/PinInput.tsx, components/ui/Button.tsx, components/ui/Layout.tsx, components/ui/Text.tsx, screens/Home/MyVcs/IdInputModal.tsx, screens/Home/MyVcs/OtpVerificationModal.tsx, screens/Home/MyVcsTab.tsx, shared/commonUtil.ts
This PR is for issue: https://mosip.atlassian.net/browse/INJI-334
=> feat(INJI-334): add testID for VC download flow

components/PinInput.tsx, components/ui/SetupPicker.tsx, screens/Home/IntroSlidersScreen.tsx, screens/SetupLanguageScreen.tsx, screens/WelcomeScreen.tsx
PR for issue: https://mosip.atlassian.net/browse/INJI-335
=> testIds for intro and language screens

components/PasscodeVerify.tsx, screens/AuthScreen.tsx, screens/PasscodeScreen.tsx
PR for issue: https://mosip.atlassian.net/browse/INJI-336
=> testIds for setPassword and confirmPassword screens

components/QrCodeOverlay.tsx, components/VcDetails.tsx, components/ui/TextItem.tsx
**[INJI-340](https://mosip.atlassian.net/browse/INJI-340)** -  Add testID, accessible and accessibility label for VC card details page
[INJI-340]: https://mosip.atlassian.net/browse/INJI-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(INJI-340): add testID for VC Detailes

components/KebabPopUp.tsx, components/VcItem.tsx, components/VcItemActivationStatus.tsx, components/VcItemContent.tsx, screens/Home/MyVcs/HistoryTab.tsx, screens/Home/MyVcs/WalletBinding.tsx
**[INJI-339](https://mosip.atlassian.net/browse/INJI-339)**  -  Add testID, accessible, and accessibilityLabel for the VC card on the home page.
[INJI-339]: https://mosip.atlassian.net/browse/INJI-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(INJI-339): Add testID's for VC Card in home page

.github/workflows/android-internal-build.yml, android/app/build.gradle
Added a job to upload apk to Github actions in internal build, every time we trigger the build.
=> Add a job to upload apk to Github actions

screens/Home/MyVcs/OtpVerificationModal.tsx
This PR is for issue 322: https://mosip.atlassian.net/browse/INJI-322
=> remove resend msg timer after timer ends

.github/workflows/ios-automation-build.yml, ios/fastlane/Fastfile, package-lock.json, package.json
- Added a new workflow for automation build in ios.
- Removed the smart share library, since there is duplication error caused in Xcode and also it is not used anymore.
=> Inji- 404 - ios automation build 

ios/Inji.xcodeproj/project.pbxproj, ios/Podfile.lock, screens/Scan/ScanLayout.tsx, screens/Scan/ScanLayoutController.ts
This is happening because in iOS rendering of one modal over another is not supported.
=> Inji 364 fix ios success message popup

.github/workflows/android-internal-build.yml
=> refactor(INJI-410,414): add eldoria, veridonia as options in android internal build

locales/en.json
feat(INJI-410): Update copy text message for QR login flow and unlock application page
=> feat(INJI-410): Update copy text messages

locales/en.json
feat(INJI-414): Update copy text message for QR login flow and unlock application page
=> feat(INJI-414): Update copy text messages

machines/QrLoginMachine.ts, machines/VCItemMachine/EsignetMosipVCItem/EsignetMosipVCItemMachine.ts, machines/bleShare/request/requestMachine.ts, machines/bleShare/scan/scanMachine.ts, machines/vc.ts, screens/Home/HomeScreenMachine.ts, screens/Home/MyVcsTabMachine.ts, screens/QrLogin/QrLoginController.ts, screens/Scan/SendVcScreen.tsx, screens/VerifyIdentityOverlay.tsx
**Changes Done as a part of this PR :**
[INJI-420](https://mosip.atlassian.net/browse/INJI-420) - User should be able to share downloaded VC via BLE
[INJI-421](https://mosip.atlassian.net/browse/INJI-421) - User should be able to use downloaded VC to login in E-Signet
[INJI-423](https://mosip.atlassian.net/browse/INJI-423) - VcItemDetails is not opening at some times.
add vc via OTP popup is not opening some times, when we go inside issuers screen and come back and try again.
[INJI-420]: https://mosip.atlassian.net/browse/INJI-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJI-421]: https://mosip.atlassian.net/browse/INJI-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJI-423]: …
=> fix(inji-420): refactoring esignet vc sharing and login cases.

.husky/pre-commit, package.json, tools/talisman/talisman-precommit.sh
This PR is for issue: https://mosip.atlassian.net/browse/INJI-413
=> talisman check for pre-commit and pre-push hooks

screens/QrLogin/QrLoginSuccessMessage.tsx
**[INJI-546](https://mosip.atlassian.net/browse/INJI-546)**:- The button name in the "Status" page is not matching as per the requirement provided.
[INJI-546]: https://mosip.atlassian.net/browse/INJI-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[Status Screen](https://github.com/mosip/inji/assets/106086523/09d36dd6-6ab4-4aa0-bac9-ca484bd0445e)
=> Fix(INJI-546): Button name in Status page is changed to OK thus issue got fixed.

injitest/src/main/java/inji/pages/AddNewCardPage.java, injitest/src/main/java/inji/pages/CredentialRegistryPage.java, injitest/src/main/java/inji/pages/DetailedVcViewPage.java, injitest/src/main/java/inji/pages/EsignetLoginPage.java, injitest/src/main/java/inji/pages/OtpVerificationPage.java, injitest/src/main/java/inji/pages/ReceiveCardPage.java, injitest/src/main/java/inji/pages/ScanPage.java, injitest/src/main/java/inji/pages/SetPasscode.java, injitest/src/main/java/inji/pages/SettingsPage.java, injitest/src/test/java/androidTestCases/CredentialRegistryTest.java, injitest/src/test/java/androidTestCases/DeletingVcTest.java, injitest/src/test/java/androidTestCases/NoNetworkAndroidTest.java, injitest/src/test/java/androidTestCases/PinVcTest.java, injitest/src/test/java/androidTestCases/ReceiveCardTest.java, injitest/src/test/java/androidTestCases/VcDownloadAndVerifyUsingEsignetTest.java, injitest/src/test/java/androidTestCases/VerifyHistoryTest.java, injitest/testng.xml
added testcases for esignet.
downloadAndVerifyVcUsingUinViaEsignet
downloadAndVerifyVcUsingVidViaEsignet
downloadVcUsingUinViaEsignetNoInternateOpenScan
downloadVcViaEsignetAndPinUnpinWithNoNetwork
downloadAndVerifyVcInInvalidEnvForEsignet
downloadAndVerifyVcInNewEnvForEsignet
=> https://mosip.atlassian.net/browse/MOSIP-30442  added esignet testcases

ios/Inji.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
- due to some limitations & time constraints I've made changes to *.pbxproj file via `BSD sed` instead of spending more time asking question in forums or in Fastlane GitHub issues
=> ci(INJI-564): use BSD sed to replace strings in pbxproj

ios/fastlane/Fastfile
Fixes Fastlane sed errors --> https://github.com/mosip/inji/actions/runs/7140879024/job/19447035814#step:6:90
=> ci(INJI-564): fix quoting in sed script

.talismanrc, ios/fastlane/Fastfile
Fixes Fastlane sed errors --> https://github.com/mosip/inji/actions/runs/7140879024/job/19447035814#step:6:90
=> ci(INJI-564): fix broken iOS Fastlane script

.talismanrc, machines/store.ts
This Pr is for issue: https://mosip.atlassian.net/browse/INJI-555
to handle uninstall in ios
https://www.npmjs.com/package/react-native-secure-key-store
=> ios data loss and crash after vc activation

screens/Scan/SendVcScreen.tsx
=> [INJI-577] fix button alignment sendVcScreen

components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, screens/Scan/SendVcScreen.tsx
**_Attaching screenshots_**
**iPhone 7**
**Android**
1. Realme c20
2. Realme c30s
=> [INJI-577] fix button alignment in SendVcScreen

machines/auth.ts, machines/faceScanner.ts, package-lock.json, package.json, shared/commonUtil.ts, shared/commonprops/commonProps.ts
[INJI-624] - remove iriscan facesdk and provide support to integrate any facesdk for face verification
[INJI-624]: https://mosip.atlassian.net/browse/INJI-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJI-624] - add support for face verification

components/ui/Loader.tsx, components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, screens/Issuers/IssuersScreen.tsx, screens/Scan/ScanLayout.tsx, screens/Scan/ScanLayoutController.ts, screens/Scan/SendVcScreen.tsx
**Before changes**
**After changes**
=> [INJI-156] fix duplicate hint shown in VC share in progress screen

components/HelpScreen.tsx, components/VC/MosipVCItem/MosipVCItemDetails.tsx, components/ui/Modal.tsx, screens/Home/ViewVcModal.tsx, screens/HomeScreenLayout.tsx, screens/QrLogin/MyBindedVcs.tsx, screens/QrLogin/QrConsent.tsx, screens/QrLogin/QrLoginSuccessMessage.tsx, screens/Settings/AboutInji.tsx, screens/Settings/ReceivedCardsModal.tsx, screens/Settings/SettingScreen.tsx, screens/VerifyIdentityOverlay.tsx
=> [INJI-620] fix detail view alignment

.talismanrc, App.tsx, components/MessageOverlay.tsx, components/ui/themes/PurpleTheme.ts, screens/Home/MyVcs/OtpVerificationModal.tsx, screens/Home/MyVcsTab.tsx, screens/Issuers/IssuersScreen.tsx, screens/Request/ReceiveVcScreen.tsx, screens/Request/RequestLayout.tsx, screens/Scan/ScanLayoutController.ts, screens/Scan/ScanScreen.tsx
=> [INJI-692&694] fix overlay height and background border color in purple

.talismanrc, package-lock.json, package.json, shared/fileStorage.ts, shared/storage.ts
* also bump up secure-keystore to fix INJI-612
=> [INJI-699] remove .hmac & .hmace files created due to INJI-612

package-lock.json, package.json
We have used 0.2.6 fixed version.
=> [INJI-763] - Use fixed version for Iriscan library

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/io/mosip/residentapp/MainApplication.java, android/app/src/main/java/io/mosip/residentapp/ODKIntentModule.java, android/app/src/main/java/io/mosip/residentapp/ODKIntentPackage.java, lib/react-native-odk-intent/ODKIntentModule.ts, machines/app.ts, machines/app.typegen.ts, machines/bleShare/request/requestMachine.ts, machines/bleShare/request/requestMachine.typegen.ts, screens/MainLayout.tsx
Completes https://github.com/idpass/inji/issues/183
Demo of this feature:
https://www.loom.com/share/21ca2d90e5184ebea7f30482432e0b07?sid=74f70345-fb9f-46c2-ad51-925360a3a928
=> Add ODK integration using Android intents

.talismanrc, components/BackupAndRestoreBannerNotification.tsx, components/BannerNotification.tsx, components/VC/MosipVCItem/MosipVCItemContent.tsx, components/openId4VCI/Issuer.tsx, components/ui/Loader.tsx, components/ui/LoaderAnimation.tsx, components/ui/svg.tsx, screens/Home/IntroSlidersScreen.tsx, screens/Home/MyVcsTab.tsx, screens/Settings/DataBackupAndRestore.tsx, screens/backupAndRestore/BackupAndRestoreScreen.tsx
testIDs added for - Inji tour guide slides, banner notification, issuer component
=> [INJIMOB-856] add testIds

lib/react-native-odk-intent/ODKIntentModule.ts, machines/bleShare/request/requestMachine.ts, types/VC/ExistingMosipVC/vc.ts
=> Fix issue in ODK Collect / CommCare integration

.github/pull_request_template.md, README.md
Update Outdated ReadMe with Latest Details Linked with Inji Docs 
[INJIMOB-941](https://mosip.atlassian.net/browse/INJIMOB-941)
NA
[INJIMOB-941]: https://mosip.atlassian.net/browse/INJIMOB-941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-941] : inji readme update

locales/ara.json
[INJIMOB-985](https://mosip.atlassian.net/browse/INJIMOB-985):-  Fixed missing translation for all languages in backup and restore flow.
[INJIMOB-985]: https://mosip.atlassian.net/browse/INJIMOB-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[Respective Screenshot](https://github.com/mosip/inji/assets/106086523/f5a608de-2452-4201-a1c4-b2ee05e5a5ce)
=> [INJIMOB-985]: Fixed Arabic translation in the flow of backup and respective.

machines/VerifiableCredential/VCItemMachine/VCItemActions.ts, machines/VerifiableCredential/VCItemMachine/VCItemMachine.ts, machines/VerifiableCredential/VCItemMachine/VCItemMachine.typegen.ts, screens/Scan/ScanScreenController.ts
- Fixed the Pin and Unpin feature not working properly in detailed view
- Fixed the issue of View Activity Log and Remove kebab menu options not working in Iphone
=> [Injimob-999] fix the issues of kebab menu and pin feature

screens/MainLayout.tsx
=> [INJIMOB-1279] show tab label as per current language in appium inspector

.talismanrc, components/ActivityLogEvent.ts, components/VC/Views/VCCardViewContent.tsx, machines/Issuers/IssuersActions.ts, machines/Issuers/IssuersGuards.ts, machines/Issuers/IssuersMachine.ts, machines/Issuers/IssuersMachine.typegen.ts, machines/Issuers/IssuersService.ts, machines/VerifiableCredential/VCItemMachine/VCItemActions.ts, machines/bleShare/request/requestMachine.ts, machines/bleShare/scan/scanMachine.ts, package-lock.json, package.json, shared/cryptoutil/cryptoUtil.ts, shared/openId4VCI/Utils.ts
- Changed RSA bit size to 1024
- Do the VC verification only for MOSIP OTP and esignet(MOSIP) VC
- Remove issuer hardcoding for **rendering id type, activation status and supporting multiple credential type**
[INJIMOB-1369](https://mosip.atlassian.net/browse/INJIMOB-1369)
[INJIMOB-1369]: https://mosip.atlassian.net/browse/INJIMOB-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1369] Change rsa bit size to 1024

components/VCVerification.tsx, components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, machines/Issuers/IssuersActions.ts, machines/Issuers/IssuersGuards.ts, machines/Issuers/IssuersMachine.ts, machines/Issuers/IssuersMachine.typegen.ts, machines/VerifiableCredential/VCItemMachine/VCItemActions.ts, machines/VerifiableCredential/VCItemMachine/VCItemGaurds.ts, machines/VerifiableCredential/VCItemMachine/VCItemMachine.ts, machines/VerifiableCredential/VCItemMachine/VCItemMachine.typegen.ts, shared/vcjs/verifyCredential.ts
Updating the Issuer actions to fix the go back issue.
=> [Injimob-695]: Go back issue fixed for Verification error in Esignet Flow

components/QrCodeOverlay.tsx
> Generating the QR always using the VC data
=> generate QR always

.talismanrc, App.tsx, components/FaceScanner.tsx, components/QrScanner.tsx, components/VC/common/VCUtils.tsx, components/kebabMenuUtils.ts, components/ui/Loader.tsx, components/ui/svg.tsx, components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, locales/ara.json, locales/en.json, locales/fil.json, locales/hin.json, locales/kan.json, locales/tam.json, machines/app.ts, screens/QrLogin/QrLogin.tsx, screens/Request/ReceiveVcScreen.tsx, screens/Scan/ScanLayout.tsx, screens/Scan/ScanScreen.tsx, screens/Scan/SendVcScreen.tsx, screens/VerifyIdentityOverlay.tsx, shared/openId4VCI/Utils.ts
> Syncing qa-develop with develop branch for internal release
> Example : [INJIMOB-1411](https://mosip.atlassian.net/browse/INJIMOB-1411)
[INJIMOB-1411]: https://mosip.atlassian.net/browse/INJIMOB-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Release-25-05-2024] Sprint 28

.talismanrc, ios/Inji-bridging-header.h, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/RNVCIClientModule.m, ios/RNVCIClientModule.swift, shared/vciClient/VciClient.ts
> The changes in this PR are for the VC downloading from the inji-vci-client-ios library 
> Example : [INJIMOB-1313](https://mosip.atlassian.net/browse/INJIMOB-1313)
[INJIMOB-1313]: https://mosip.atlassian.net/browse/INJIMOB-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [injimob-1313] add native module briding files for inji vci client ios

App.tsx, android/app/build.gradle, android/app/src/main/java/io/mosip/residentapp/InjiPackage.java, android/app/src/main/java/io/mosip/residentapp/MainApplication.java, android/app/src/main/java/io/mosip/residentapp/RNSecureKeystoreModule.java, android/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/Podfile.lock, machines/Issuers/IssuersService.ts, machines/VerifiableCredential/VCItemMachine/VCItemServices.ts, machines/store.ts, machines/store.typegen.ts, package-lock.json, package.json, shared/cryptoutil/cryptoUtil.ts, shared/storage.ts
> native library integrated of secure keystore in Inji
> Example : [INJIMOB-1417]:https://mosip.atlassian.net/browse/INJIMOB-1417?atlOrigin=eyJpIjoiNDkzZTFmM2EzY2Y0NGE1OGI4YmFmZDc0NWUxNWE1NzgiLCJwIjoiaiJ9
[INJIMOB-1417]: https://mosip.atlassian.net/browse/INJIMOB-1417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1417]: integrating native library of secure-keystone in Inji

.talismanrc, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [injimob-1313] update inji-vci-client library version for ios

ios/fastlane/Fastfile
=> [INJIMOB-1339] - add allowProvisioningUpdates

components/VC/common/VCUtils.tsx
Reverse sync qa-develop branch
=> Reverse sync qa develop

ios/Inji.xcodeproj/project.pbxproj
=> [INJIMOB-1339] - revert codesigning changes

ios/Inji.xcodeproj/project.pbxproj
=> Injjimob 1339 ios pipeline fix

ios/fastlane/Fastfile
=> [INJIMOB-1339 remove auto signing

ios/fastlane/Fastfile
=> [INJIMOB-1339] - update xcode

injitest/androidRegression.xml, injitest/androidSanity.xml, injitest/iosRegression.xml, injitest/iosSanity.xml, injitest/src/main/java/inji/pages/AboutInjiPage.java, injitest/src/main/java/inji/pages/SharePage.java, injitest/src/test/java/androidTestCases/AboutInjiTest.java, injitest/src/test/java/iosTestCases/AboutInjiTest.java
automated to verify whether appID and the Tuvali version is available on the app
https://mosip.atlassian.net/browse/INJIMOB-1430
=> automate to verify appID and tuvali version 

machines/bleShare/scan/scanMachine.ts
[INJIMOB-1242](https://mosip.atlassian.net/issues/INJIMOB-1242)
[INJIMOB-1242]: https://mosip.atlassian.net/browse/INJIMOB-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1242]: fix face verification banner toaster for normal sharing

.github/workflows/ui-automation.yml, injitest/automation_trigger.sh
=> [DSD-5562]

ios/Inji.xcodeproj/project.pbxproj
=> [INJIMOB] - Update marketing version in IOS

android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
=> [ INJIMOB ] - Update bundle id for both IOS and Android

shared/storage.ts, shared/vcjs/verifyCredential.ts
> Verify the VCs during backup restoration
>  [INJIMOB-797](https://mosip.atlassian.net/browse/INJIMOB-797)
[INJIMOB-797]: https://mosip.atlassian.net/browse/INJIMOB-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB 797]:  Verify restored VCs

ios/Inji.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
=> [INJIMOB] dynamically change profile name based on app flavor

android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
=> Injimob update ios version update

.env
=> [INJIMOB] - Turn off liveness detection

components/CopilotTooltip.tsx, components/CopilotTooltipController.tsx, shared/constants.ts
> Change tourguide title and description testID 
=> Change tourguide title and description testID

components/QrCodeOverlay.tsx, ios/Inji.xcodeproj/project.pbxproj, shared/constants.ts
> (https://github.com/mosip/inji/pull/1546)
=> [INJIMOB-1552] change qr ecc and add quiet zone

android/app/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Dependency changes
> https://mosip.atlassian.net/browse/INJIMOB-1554
=> [INJIMOB-1554] change dependency versions  for release

machines/VerifiableCredential/VCItemMachine/VCItemMachine.ts
>State machine changes
>https://mosip.atlassian.net/browse/INJIMOB-1491
=> [INJIMOB-1491] change in vc item machine logging actions

.env
=> [INJIMOB-1597]: toggle off liveness

components/FaceScanner/FaceCompare.tsx, components/FaceScanner/FaceScanner.tsx, machines/faceScanner.ts
> Example : [INJIMOB-1603](https://mosip.atlassian.net/browse/INJIMOB-1603)
=> [INJIMOB-1603]: Fix camera blank screen issue

shared/storage.ts
> Example : [INJIMOB-797](https://mosip.atlassian.net/browse/INJIMOB-791)
[INJIMOB-797]: https://mosip.atlassian.net/browse/INJIMOB-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-797]: VC Verification on restore

README.md, shared/api.ts
> use /v1/mimoto for mimoto apis.
> Example : [INJIMOB-1666](https://mosip.atlassian.net/browse/INJIMOB-1666)
[INJIMOB-1666]: https://mosip.atlassian.net/browse/INJIMOB-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1666] - use /v1/mimoto for mimoto apis.

components/CopilotTooltip.tsx, components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, shared/constants.ts
> Fixed the alignment issue between the buttons and the end of the tour guide box
> [INJIMOB-1492](https://mosip.atlassian.net/issues/INJIMOB-1492)
> [INJIMOB-1503](https://mosip.atlassian.net/issues/INJIMOB-1503)
> https://github.com/user-attachments/assets/ceaacc55-d35f-4cce-a061-c4b3afb0d7cd
[INJIMOB-1492]: https://mosip.atlassian.net/browse/INJIMOB-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-1503]: https://mosip.atlassian.net/browse/INJIMOB-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1492]: fix alignment issue in inji tour guide

android/app/build.gradle
> updated android dependency version-Pixelpass and Securekeystore
=> [INJIMOB-1093] update android dependency version

screens/Issuers/IssuersScreen.tsx
> unable to scroll the page in the issuer's screen
> [INJIMOB-1574](https://mosip.atlassian.net/browse/INJIMOB-1574)
[INJIMOB-1574]: https://mosip.atlassian.net/browse/INJIMOB-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1574]: fix scroll issue in issuers screen

android/app/build.gradle, components/VC/Views/VCCardView.tsx, components/VC/Views/VCCardViewContent.tsx, components/VC/Views/VCDetailView.tsx, components/VC/common/VCUtils.tsx, components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, ios/Inji.xcodeproj/project.pbxproj, machines/Issuers/IssuersActions.ts, machines/Issuers/IssuersMachine.ts, machines/Issuers/IssuersMachine.typegen.ts, machines/Issuers/IssuersService.ts, machines/VerifiableCredential/VCItemMachine/VCItemMachine.typegen.ts, machines/VerifiableCredential/VCItemMachine/VCItemServices.ts, machines/VerifiableCredential/VCMetaMachine/VCMetaMachine.typegen.ts, machines/VerifiableCredential/VCMetaMachine/vc.d.ts, machines/app.typegen.ts, machines/store.typegen.ts, screens/Home/HomeScreenMachine.typegen.ts, screens/Home/ViewVcModal.tsx, screens/Request/ReceiveVcScreen.tsx, shared/api.ts, shared/openId4VCI/Utils.ts
> This PR includes draft 13 changes. Major changes include:
- Change in issuer model.
- Removal of issuerconfigfetch api
- Addition of bg image property.
> Example : https://mosip.atlassian.net/jira/software/c/projects/INJIMOB/boards/91?selectedIssue=INJIMOB-1093
=> [INJIMOB-1093] draft13 changes

screens/Home/MyVcs/IdInputModal.tsx
> The download ID button text on the addVC screen has been corrected as per the latest wireframe.
> Example : [INJIMOB-76](https://mosip.atlassian.net/browse/INJIMOB-76)
> 
[INJIMOB-76]: https://mosip.atlassian.net/browse/INJIMOB-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-76]: download ID button text correction

android/app/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
>  update dependencies from released version
=> [DSD-5825] - update dependencies from released version

.github/workflows/internal-build.yml, android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj
1. Changed the app version to 0.14.0.
2. Liveness off by default for workflow.
[INJIMOB-1782](https://mosip.atlassian.net/browse/INJIMOB-1782)
[INJIMOB-1782]: https://mosip.atlassian.net/browse/INJIMOB-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1782]: Sprint-33 release

ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, machines/Issuers/IssuersMachine.ts, shared/openId4VCI/Utils.ts
>   Removed additional header field from authorisation configuration
>https://mosip.atlassian.net/browse/INJIMOB-1093
=> [INJIMOB-1093] refactor authorization config

machines/Issuers/IssuersService.ts
> added id field in credential type object
>https://mosip.atlassian.net/browse/INJIMOB-1093
=> [INJIMOB-1093] add id in credential type object

.env, shared/telemetry/TelemetryUtils.js
> Update data push endpoint of Telemetry
> Example : [INJIMOB-1729](https://mosip.atlassian.net/browse/INJIMOB-1729)
[INJIMOB-1729]: https://mosip.atlassian.net/browse/INJIMOB-1729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1729]: update data push endpoint of telemetry

injitest/src/main/java/inji/pages/AddNewCardPage.java, injitest/src/main/java/inji/pages/BasePage.java, injitest/src/main/java/inji/pages/EsignetLoginPage.java, injitest/src/test/java/androidTestCases/ChangeLanguageTest.java, injitest/src/test/java/iosTestCases/ChangeLanguageTest.java
MOSIP-35204 automation fixes for sprint 33 and updated correct assert messages.
=> MOSIP-35204 automation fixes for sprint 33

.env, android/build.gradle, shared/request.ts, shared/telemetry/TelemetryUtils.js
> Bump up target sdk version to 34
> Example : [INJIMOB-1781](https://mosip.atlassian.net/browse/INJIMOB-1781)
[INJIMOB-1781]: https://mosip.atlassian.net/browse/INJIMOB-1781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> INJIMOB 1781: bump up target sdk version to 34

.github/workflows/ui-automation.yml
[DSD-6004] Updated browserstack-web.yml to push artifacts to s3 bucket.
[DSD-6004]: https://mosip.atlassian.net/browse/DSD-6004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DSD-6004] Updated browserstack-web.yml to push artifacts to s3 bucket.

shared/openId4VCI/Utils.ts
> fix fallback issuer vc not rendering. Updated condition for checking order field in well known.
>https://mosip.atlassian.net/browse/INJIMOB-1850
=> [INJIMOB-1850] fix fallback issuer vc not rendering

components/kebabMenuUtils.ts
> Update logic to have share with selfie option and Vc activation only for Mosip VC
> [INJIMOB-1820](https://mosip.atlassian.net/browse/INJIMOB-1820)
> [INJIMOB-1858](https://mosip.atlassian.net/browse/INJIMOB-1858)
[INJIMOB-1820]: https://mosip.atlassian.net/browse/INJIMOB-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-1858]: https://mosip.atlassian.net/browse/INJIMOB-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1820 & 1858]: update logic to have share with selfie option and Vc activation only for Mosip VC

components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts
> Example : [INJIMOB-1422](https://mosip.atlassian.net/browse/INJIMOB-1422)
[INJIMOB-1422]: https://mosip.atlassian.net/browse/INJIMOB-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Injimob-1422 -  Fix camera view widening in scanner and face verification

shared/openId4VCI/Utils.ts
> fix error text for network request timed out
> Example : https://mosip.atlassian.net/browse/INJIMOB-1955
=> [INJIMOB-1955] fix error text for network request timed out

android/app/build.gradle
> update android artifacts version
=> [INJIMOB-1955] modify android artifacts version

.github/workflows/ui-automation.yml, injitest/pom.xml
[DSD-6142] Updated java21 env in workflow file after android build
=> [DSD-6142] Updated java21 env in workflow file

.github/workflows/ui-automation.yml
[DSD-6142] Updated java21 env in workflow file after build for both android and ios
[DSD-6142]: https://mosip.atlassian.net/browse/DSD-6142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DSD-6142] Updated java21 env in workflow file after build for both android and ios

android/app/build.gradle, android/fastlane/Fastfile
> Example : [INJIMOB-1970](https://mosip.atlassian.net/browse/INJIMOB-1970)
[INJIMOB-1970]: https://mosip.atlassian.net/browse/INJIMOB-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1970]: bump up dependent library version in inji

android/build.gradle
=> [INJIMOB-1781]: bump up version target sdk of inji

.github/workflows/android-custom-build.yml, android/fastlane/Fastfile, android/scripts/android-build.sh
> Example : [INJIMOB-1278](https://mosip.atlassian.net/browse/INJIMOB-1278)
[INJIMOB-1278]: https://mosip.atlassian.net/browse/INJIMOB-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1278]: Add release/debug build support to android custom build

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/io/mosip/residentapp/InjiPackage.java, android/app/src/main/java/io/mosip/residentapp/IntentData.java, android/app/src/main/java/io/mosip/residentapp/MainActivity.java, android/app/src/main/java/io/mosip/residentapp/RNQrLoginIntentModule.java, android/build.gradle, machines/app.ts, machines/app.typegen.ts, machines/bleShare/scan/scanActions.ts, machines/bleShare/scan/scanMachine.ts, machines/bleShare/scan/scanMachine.typegen.ts, machines/bleShare/scan/scanModel.ts, machines/bleShare/scan/scanSelectors.ts, routes/index.ts, screens/MainLayout.tsx, screens/Scan/ScanLayoutController.ts
> QR login via deeplink 
> Example : [INJIMOB-1911](https://mosip.atlassian.net/browse/INJIMOB-1911)
[INJIMOB-1911]: https://mosip.atlassian.net/browse/INJIMOB-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1911]: add logic for QR login via deeplink

android/app/build.gradle
> Updated android dependencies to patch release versions
=> [INJIMOB-1970] update android dependencies

components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, screens/Home/MyVcsTab.tsx, screens/Issuers/IssuersScreen.tsx
> Example : [INJIMOB-1837](https://mosip.atlassian.net/browse/INJIMOB-1837)
[INJIMOB-1837]: https://mosip.atlassian.net/browse/INJIMOB-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> INJIMOB - 1837 - Fix cross icon pressable issue in search bar.

shared/cryptoutil/cryptoUtil.ts
> [INJIMOB-1874](https://mosip.atlassian.net/browse/INJIMOB-1874&#41)
[INJIMOB-1874]: https://mosip.atlassian.net/browse/INJIMOB-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1874] fix vc download due to key-pair mismatch

shared/openId4VCI/Utils.ts
> fixed ordering of user priority keys
> [INJIMOB-1874](https://mosip.atlassian.net/browse/INJIMOB-1874&#41)
[INJIMOB-1874]: https://mosip.atlassian.net/browse/INJIMOB-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1874] fix hardcoded order of keys

ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, machines/Issuers/IssuersSelectors.ts, screens/Issuers/IssuerScreenController.tsx, screens/Issuers/IssuersScreen.tsx, shared/CloudBackupAndRestoreUtils.ts, shared/cryptoutil/cryptoUtil.ts, shared/openId4VCI/Utils.ts
> Example : [INJIMOB-2020](https://mosip.atlassian.net/browse/INJIMOB-2020)
[INJIMOB-2020]: https://mosip.atlassian.net/browse/INJIMOB-2020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> INJIMOB-2020 - Fix VC download and Error screen toaster issue.

ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, machines/Issuers/IssuersSelectors.ts, machines/store.ts, screens/Issuers/IssuerScreenController.tsx, screens/Issuers/IssuersScreen.tsx, shared/CloudBackupAndRestoreUtils.ts, shared/cryptoutil/cryptoUtil.ts, shared/openId4VCI/Utils.ts
> Example : [INJIMOB-2020](https://mosip.atlassian.net/browse/INJIMOB-2020)
[INJIMOB-2020]: https://mosip.atlassian.net/browse/INJIMOB-2020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> INJIMOB-2020 - Fix QR login issue in iOS

injitest/src/main/java/inji/pages/AddNewCardPage.java, injitest/src/main/java/inji/pages/EsignetLoginPage.java
=> updated the accessibility id

injitest/androidRegression.xml, injitest/iosRegression.xml, injitest/src/main/java/inji/pages/AddNewCardPage.java, injitest/src/main/java/inji/pages/EsignetLoginPage.java, injitest/src/main/java/inji/pages/HomePage.java, injitest/src/test/java/androidTestCases/ChangeLanguageTest.java, injitest/src/test/java/androidTestCases/VerifyWelcomePagesTest.java, injitest/src/test/java/iosTestCases/ChangeLanguageTest.java, injitest/src/test/java/iosTestCases/VerifyWelcomePagesTest.java
INJIMOB-2023 fixed inji-wallet ui automation for Ios and android
=> INJIMOB-2023 fixed inji-wallet ui automation for Ios and android

.github/workflows/android-custom-build.yml, .github/workflows/internal-build.yml, .github/workflows/push-triggers.yml, components/CopilotTooltip.tsx, screens/Settings/SettingScreenController.ts
> bug fix for biometric toggle after inji tour guide triggered from settings screen.
> [INJIMOB-2048](https://mosip.atlassian.net/browse/INJIMOB-2048&#41)
[INJIMOB-2048]: https://mosip.atlassian.net/browse/INJIMOB-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2048] fix toogle biometric not working after inji tour guide and update workflow to use java17

shared/openId4VCI/Utils.ts
=> [INJIMOB-2005] revert harcoded token endpoint to token fetching issue

android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj
Bumped up app version to 0.15.0
> Example : [INJIMOB-2097](https://mosip.atlassian.net/browse/INJIMOB-2097)
[INJIMOB-2097]: https://mosip.atlassian.net/browse/INJIMOB-2097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> INJIMOB-2097 -  bump up app version to 0.15.0

machines/bleShare/scan/scanMachine.ts, screens/Scan/ScanLayoutController.ts
> Fix redirection issue while on share screen 
> [INJIMOB-1911](https://mosip.atlassian.net/browse/INJIMOB-1911)
[INJIMOB-1911]: https://mosip.atlassian.net/browse/INJIMOB-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1911]: fix redirection issue while on  share screen

android/app/src/main/java/io/mosip/residentapp/RNSecureKeystoreModule.java, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, machines/Issuers/IssuersGuards.ts, machines/Issuers/IssuersService.ts, machines/store.ts, screens/Home/MyVcs/AddVcModalMachine.typegen.ts, screens/SplashScreen.tsx, shared/cryptoutil/cryptoUtil.ts
> modify fetchkeypair to haskeypair to reduce keychain key retrieval  and refactor for error handling
> Example : [INJIMOB-2093](https://mosip.atlassian.net/browse/INJIMOB-2093&#41)
[INJIMOB-2093]: https://mosip.atlassian.net/browse/INJIMOB-2093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2093] modify fetchkeypair to haskeypair to reduce keychain key retrieval 

machines/QrLogin/QrLoginMachine.ts, machines/QrLogin/QrLoginSelectors.ts, machines/bleShare/scan/scanActions.ts, machines/bleShare/scan/scanMachine.ts, machines/bleShare/scan/scanMachine.typegen.ts, machines/bleShare/scan/scanSelectors.ts, machines/openID4VP/openID4VPActions.ts, machines/openID4VP/openID4VPMachine.ts, machines/openID4VP/openID4VPMachine.typegen.ts, machines/openID4VP/openID4VPModel.ts, machines/openID4VP/openID4VPSelectors.ts, machines/openID4VP/openID4VPServices.ts, screens/Issuers/IssuersScreen.tsx, screens/Scan/ScanLayout.tsx, screens/Scan/ScanLayoutController.ts, screens/Scan/ScanScreen.tsx, screens/Scan/SendVPScreen.tsx, screens/Scan/SendVPScreenController.ts, screens/Scan/VPShareOverlay.tsx
> Fixed the header and error screen issues in issuer screen
> Added background press for consent screens in ovp flows
> Fixed the invalid link transaction issue found in qr login from kebab menu flow
> [INJIMOB-2096](https://mosip.atlassian.net/browse/INJIMOB-2096)
[INJIMOB-2096]: https://mosip.atlassian.net/browse/INJIMOB-2096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Injimob 2096]  add missing flows in ovp flow & fix issues found in issuer screen, ovp & wallet binding flows

android/app/build.gradle, android/build.gradle, ios/Inji/Inji.entitlements, ios/Podfile.lock, package-lock.json, package.json
> Example : [INJIMOB-1603](https://mosip.atlassian.net/browse/INJIMOB-1603)
[INJIMOB-1603]: https://mosip.atlassian.net/browse/INJIMOB-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Injimob-1603- Expo camera, react native screens  and SDK version updates

android/app/build.gradle, android/build.gradle
---------
> Example : [INJIMOB-1603](https://mosip.atlassian.net/browse/INJIMOB-1603)
[INJIMOB-1603]: https://mosip.atlassian.net/browse/INJIMOB-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Injimob 1603 -  Expo camera, RN screens and min sdk update

README.md
- update tools version & env data in PreRequisites section
- link Inji Wallet docs for build and deployment section
> https://mosip.atlassian.net/browse/DSD-6453
=> [DSD-6453] update readme

android/app/build.gradle, ios/Inji.xcodeproj/project.pbxproj, machines/auth.ts, shared/api.ts, shared/commonUtil.ts, shared/constants.ts
The app size will increase by ~25 mb, because of bundling the face model as an asset of the app.
> Example : [INJIMOB-2125](https://mosip.atlassian.net/browse/INJIMOB-2125)
[INJIMOB-2125]: https://mosip.atlassian.net/browse/INJIMOB-2125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2125]: Bundle face model as asset of the app

components/BannerNotificationContainer.tsx, components/BannerNotificationController.tsx, locales/en.json, machines/VerifiableCredential/VCMetaMachine/VCMetaActions.ts, machines/VerifiableCredential/VCMetaMachine/VCMetaEvents.ts, machines/VerifiableCredential/VCMetaMachine/VCMetaMachine.ts, machines/VerifiableCredential/VCMetaMachine/VCMetaMachine.typegen.ts, machines/VerifiableCredential/VCMetaMachine/VCMetaModel.ts, machines/VerifiableCredential/VCMetaMachine/VCMetaSelectors.ts, shared/api.ts
> add vc download success banner
> [INJIMOB-2018](https://mosip.atlassian.net/browse/INJIMOB-2018&#41)
[INJIMOB-2018]: https://mosip.atlassian.net/browse/INJIMOB-2018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2018] add vc download success banner

shared/api.ts
>fixed caching logic, to use cache if the device is offline, for any other errors, show appropriate error messages to user.
> Example : [INJIMOB-1852](https://mosip.atlassian.net/browse/INJIMOB-1852&#41)
[INJIMOB-1852]: https://mosip.atlassian.net/browse/INJIMOB-1852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1852] fix caching logic, to use cache if the device is offline

machines/Issuers/IssuersMachine.typegen.ts, shared/cryptoutil/KeyTypes.ts, shared/cryptoutil/cryptoUtil.ts, shared/openId4VCI/Utils.ts
>fix ed key signature format for VC download
> Example : [INJIMOB-1578](https://mosip.atlassian.net/browse/INJIMOB-1578&#41)
[INJIMOB-1578]: https://mosip.atlassian.net/browse/INJIMOB-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-1578] fix ed key signature format for VC download

.gitignore, android/app/build.gradle, android/app/src/main/java/io/mosip/residentapp/RNPixelpassModule.java, components/QrCodeOverlay.tsx, components/VC/VCItemController.tsx, components/VC/Views/VCCardView.tsx, components/VC/Views/VCCardViewContent.tsx, components/VC/Views/VCDetailView.tsx, components/VC/common/VCProcessor.ts, components/VC/common/VCUtils.tsx, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/RNPixelpassModule.m, ios/RNPixelpassModule.swift, machines/Issuers/IssuersActions.ts, machines/Issuers/IssuersMachine.ts, machines/Issuers/IssuersService.ts, machines/VerifiableCredential/VCItemMachine/VCItemSelectors.ts, machines/VerifiableCredential/VCMetaMachine/vc.d.ts, machines/bleShare/request/selectors.ts, screens/Home/ViewVcModal.tsx, screens/Home/ViewVcModalController.ts, screens/Request/ReceiveVcScreen.tsx, screens/Scan/SendVPScreen.tsx, screens/Scan/SendVcScreenController.ts, shared/Utils.ts, shared/VCMetadata.ts, shared/openId4VCI/Utils.ts, shared/storage.ts
> Wallet will get the mso_mdoc Vc output from vci-client and passing it to PixelPass to convert the CBOR to JSON. The processed JSON will then be used to render VC data in UI
> Example : [INJIMOB-2160](https://mosip.atlassian.net/browse/INJIMOB-2160)
[> More info.](https://mosip.atlassian.net/browse/INJIMOB-2160?focusedCommentId=93552)
**Todos**
- update pixelpass lib version in package.swift & build.gradle
[INJIMOB-2160]: https://mosip.atlassian.net/browse/INJIMOB-2160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2160] use pixelpass for processing mmdoc data for rendering 

components/HelpScreen.tsx
> update inji docs url after docs restructure
> Example : [INJIMOB-2260](https://mosip.atlassian.net/browse/INJIMOB-2260&#41)
[INJIMOB-2260]: https://mosip.atlassian.net/browse/INJIMOB-2260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2260] update inji docs url after docs restructure

android/app/build.gradle
> [INJIMOB-2170](https://mosip.atlassian.net/browse/INJIMOB-2170)
[INJIMOB-2170]: https://mosip.atlassian.net/browse/INJIMOB-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2170] rename openid4vp artifact name to use all small case letters

ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, shared/cryptoutil/cryptoUtil.ts
> Example : [INJIMOB-2252](https://mosip.atlassian.net/browse/INJIMOB-2252)
[INJIMOB-2252]: https://mosip.atlassian.net/browse/INJIMOB-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2252]: Throw biometric cancelled error when user cancels it

.talismanrc, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, shared/vcjs/verifyCredential.ts
> update depenedency securekeystore for ios
=> [INJIMOB-2323] update depenedency securekeystore for ios

ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Example : [INJIMOB-2265](https://mosip.atlassian.net/browse/INJIMOB-2265)
[INJIMOB-2265]: https://mosip.atlassian.net/browse/INJIMOB-2265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2265]: Update openID4VP swift package

README.md
> [INJIMOB-1686](https://mosip.atlassian.net/browse/INJIMOB-1686)
[INJIMOB-1686]: https://mosip.atlassian.net/browse/INJIMOB-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2368]: update the readme

shared/vcjs/verifyCredential.ts
=> [INJIMOB-2324] add UIN/VID only to telemetry log in case of verification failure

.talismanrc, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Ticket : [INJIMOB-2368](https://mosip.atlassian.net/browse/INJIMOB-2368)
Note: Sanity done for VC download and QR code verification via inji-verify
[INJIMOB-2368]: https://mosip.atlassian.net/browse/INJIMOB-2368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2368] update the readme & tuvali, pixelpass, inji-vci-client library version

.talismanrc, machines/Issuers/IssuersActions.ts, machines/Issuers/IssuersService.ts, machines/VerifiableCredential/VCMetaMachine/vc.d.ts, shared/commonUtil.ts, shared/vcjs/verifyCredential.ts
=> Vc issue v1

.talismanrc, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, shared/VCMetadata.ts
=> [INJIMOB-2265] update openid4vp swift package commit

machines/backupAndRestore/backup.typegen.ts, machines/backupAndRestore/backupAndRestoreSetup.typegen.ts, machines/settings.ts, machines/settings.typegen.ts, screens/Settings/DataBackupAndRestore.tsx, screens/Settings/SettingScreenController.ts, screens/Settings/SettingsKeyManagement.tsx
> remove the new label from backup restore
=> [INJIMOB-2260] remove new label from backupRestore and KeyManagement feature

ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [DSD-6453] inji-wallet 0.14.0 release

ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, machines/app.ts, machines/auth.ts, machines/settings.ts, machines/store.ts
> Example : [INJIMOB-2310](https://mosip.atlassian.net/browse/INJIMOB-2310)
[INJIMOB-2310]: https://mosip.atlassian.net/browse/INJIMOB-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Injimob 2310 - Handle iOS biometric negative scenarios

components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, i18n.ts, locales/pt.json, screens/Home/MyVcs/HistoryTab.tsx, screens/MainLayout.tsx, screens/Settings/AboutInji.tsx
> Example : [INJIMOB-2384](https://mosip.atlassian.net/browse/INJIMOB-2384)
[INJIMOB-2384]: https://mosip.atlassian.net/browse/INJIMOB-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2313]: Add new locale Portuguese and refactor

locales/pt.json
> Example : [INJIMOB-2384](https://mosip.atlassian.net/browse/INJIMOB-2384)
[INJIMOB-2384]: https://mosip.atlassian.net/browse/INJIMOB-2384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2384]: Add missing translations for Portuguese locale

shared/VCMetadata.ts
> Example : [INJIMOB-2313](https://mosip.atlassian.net/browse/INJIMOB-2313)
[INJIMOB-2313]: https://mosip.atlassian.net/browse/INJIMOB-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2313]: Return empty string when display id is not present

components/VC/Views/VCCardViewContent.tsx, components/VC/Views/VCDetailView.tsx, components/VC/common/VCItemField.tsx, components/VC/common/VCUtils.tsx
> Example : [INJIMOB-2313](https://mosip.atlassian.net/browse/INJIMOB-2313)
[INJIMOB-2313]: https://mosip.atlassian.net/browse/INJIMOB-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2313]: Modify fallback colors for vc rendering

.env, .github/workflows/android-custom-build.yml, .github/workflows/internal-build.yml, .github/workflows/ui-automation.yml, README.md, components/ActivityLogEvent.ts
> Orange theme has been replaced by gradient.
> Example : [INJIMOB-2260](https://mosip.atlassian.net/browse/INJIMOB-2260&#41)
[INJIMOB-2260]: https://mosip.atlassian.net/browse/INJIMOB-2260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2260] change theme to gradient from workflows

ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/RNSecureKeystoreModule.m, ios/RNSecureKeystoreModule.swift, machines/backupAndRestore/backupRestore.typegen.ts, shared/CloudBackupAndRestoreUtils.ts
> fix multiple ios signin issue.
> Example : [INJIMOB-2449](https://mosip.atlassian.net/browse/INJIMOB-2449&#41)
[INJIMOB-2449]: https://mosip.atlassian.net/browse/INJIMOB-2449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2449] fix multiple ios signin issue

injitest/pom.xml
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JAVA-COMMONSCOLLECTIONS-30078
- https://snyk.io/vuln/SNYK-JAVA-COMMONSCOLLECTIONS-6056408
- https://snyk.io/vuln/SNYK-JAVA-LOG4J-572732
- https://snyk.io/vuln/SNYK-JAVA-ORGJSON-5488379
- https://snyk.io/vuln/SNYK-JAVA-ORGJSON-5962464
- https://snyk.io/vuln/SNYK-JAVA-ORGSELENIUMHQSELENIUM-6062318
- https://snyk.io/vuln/SNYK-JAVA-LOG4J-2316893
- https://snyk.io/vuln/SNYK-JAVA-LOG4J-2342645
- https://snyk.io/vuln/SNYK-JAVA-LOG4J-2342646
- https://snyk.io/vuln/SNYK-JAVA-LOG4J-2342647
- https://snyk.io/vuln/SNYK-JAVA-COMMONSCOLLECTIONS-472711
- https://snyk.io/vuln/SNYK-JAVA-ORGKEYCLOAK-8186433
- https://snyk.io/vuln/SNYK-JAVA-SOFTWAREAMAZONION-6153869
- https://snyk.io/vuln/SNYK-JAVA-IONETTY-6483812
- …
=> [MOSIP-37071] fix: injitest/pom.xml to reduce vulnerabilities

android/app/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, machines/openID4VP/openID4VPMachine.ts, machines/openID4VP/openID4VPMachine.typegen.ts, machines/openID4VP/openID4VPServices.ts, shared/cryptoutil/cryptoUtil.ts
=> made changes for ovp demo

android/app/src/main/java/io/mosip/residentapp/InjiOpenID4VPModule.java, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/RNOpenID4VPModule.m, ios/RNOpenID4VPModule.swift, machines/openID4VP/openID4VPGuards.ts, machines/openID4VP/openID4VPMachine.ts, machines/openID4VP/openID4VPMachine.typegen.ts, machines/openID4VP/openID4VPServices.ts, shared/openID4VP/OpenID4VP.ts
… 
> Wallet will fetch the openid4vp client validation property and pass it to the libraries and based on this value libraries will decide whether it should perform the client validation or not.
> Example : [INJIMOB-2538](https://mosip.atlassian.net/browse/INJIMOB-2538)
[INJIMOB-2538]: https://mosip.atlassian.net/browse/INJIMOB-2538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2538] fetch the openid4vp sharing flow client validation property from inji default properties file and pass it to library

.github/workflows/ui-automation.yml
=> [MOSIP-38397] Upgraded actions/cache version

.talismanrc, machines/openID4VP/openID4VPModel.ts, machines/openID4VP/openID4VPServices.ts, screens/Scan/SendVPScreenController.ts, shared/openID4VP/OpenID4VP.ts
> Set the default signing algorithm to use ed25519 for signing the vp_token in VP sharing flow
> Example : [INJIMOB-2550](https://mosip.atlassian.net/browse/INJIMOB-2550)
[INJIMOB-2550]: https://mosip.atlassian.net/browse/INJIMOB-2550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2550] use ed25519 key type for signing the vp token in VP sharing flow

machines/Issuers/IssuersGuards.ts
> fix syntax error in gaurd condition
=> [INJIMOB-2415] fix syntax error in gaurd condition

.github/workflows/push-triggers.yml
=> [MOSIP-38411] rename main to master

android/app/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
> Example : [INJIMOB-2325](https://mosip.atlassian.net/browse/INJIMOB-2325)
[INJIMOB-2325]: https://mosip.atlassian.net/browse/INJIMOB-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2325]: Update Openid4vp package with client id scheme and request uri support

.github/workflows/internal-build.yml, ios/fastlane/Fastfile
> modify ios/fastfile and internal build workflow to ena…ble automation build without testflight deploy
> Example : [INJIMOB-2878](https://mosip.atlassian.net/browse/INJIMOB-2878&#41)
[INJIMOB-2878]: https://mosip.atlassian.net/browse/INJIMOB-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2878] modify ios/fastfile and internal build workflow to ena…ble automation build without testflight deploy

ios/fastlane/Fastfile
> modify ios/fastfile to fix automation build artifact path
> Example : [INJIMOB-2878](https://mosip.atlassian.net/browse/INJIMOB-2878&#41)
[INJIMOB-2878]: https://mosip.atlassian.net/browse/INJIMOB-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2878] modify ios/fastfile to fix automation build artifact path

.github/workflows/ios-custom-build.yml
> add custom workflow for ios build
> Example : [INJIMOB-2878](https://mosip.atlassian.net/browse/INJIMOB-2878&#41)
[INJIMOB-2878]: https://mosip.atlassian.net/browse/INJIMOB-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2878] add custom workflow for ios build

components/ui/themes/DefaultTheme.ts, components/ui/themes/PurpleTheme.ts, screens/Scan/SendVPScreen.tsx
> Example : [INJIMOB-2881](https://mosip.atlassian.net/browse/INJIMOB-2881&#41)
[INJIMOB-2881]: https://mosip.atlassian.net/browse/INJIMOB-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2881]: Truncate client name text in send vp screen

docs/OpenID4VP.md
> Example : [INJIMOB-2903](https://mosip.atlassian.net/browse/INJIMOB-2903&#41)
=> [INJIMOB-2903] - Openid4vp sequence diagram

docs/mdoc-support.md
> Add doc content for mdoc support
> [INJIMOB-2903](https://mosip.atlassian.net/browse/INJIMOB-2903)
=> [INJIMOB-2903] add mdoc support document

docs/OpenID4VP.md
> Example : [INJIMOB-2903](https://mosip.atlassian.net/browse/INJIMOB-2903&#41)
=> [INJIMOB-2903]: Add OpenID4VP sequence diagram

docs/KeyManagement.md
> add design doc for keymanagement feature
> Example : [INJIMOB-2903](https://mosip.atlassian.net/browse/INJIMOB-2903&#41)
=> [INJIMOB-2903] add design doc for keymanagement feature

docs/authorization-server-wellknown-discovery.md, docs/mdoc-support.md
> add auth server wellknown discovery document
>  [INJIMOB-2903](https://mosip.atlassian.net/browse/INJIMOB-2903&#41)
=> [INJIMOB-2903] add auth server wellknown discovery document

android/app/build.gradle
[INJIMOB-2907]: Update tuvali version to 0.5.2-SNAPSHOT
[INJIMOB-2907]: https://mosip.atlassian.net/browse/INJIMOB-2907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2907]: [Release-0.16.x]Update tuvali version to 0.5.2-SNAPSHOT

android/app/build.gradle
[INJIMOB-2907]: [Develop]Update Tuvali version to 0.5.2-SNAPSHOT
[INJIMOB-2907]: https://mosip.atlassian.net/browse/INJIMOB-2907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2907]: [Develop]Update Tuvali version to 0.5.2-SNAPSHOT

i18n.ts
=> Update i18n.ts update es label

machines/openID4VP/openID4VPServices.ts
> support did:jwk to send ed25519 public key to verifier in ovp flow
> [INJIMOB-2983](https://mosip.atlassian.net/browse/INJIMOB-2983&#41)
[INJIMOB-2983]: https://mosip.atlassian.net/browse/INJIMOB-2983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2983] support did:jwk to send ed25519 public key to verifier in ovp flow

android/app/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, machines/openID4VP/openID4VPServices.ts
Other changes
- update openid4vp swift library version
- update openid4vp kotlin library version
- fix vp token metadata response creation
=> [INJIMOB-2978]  update module dependencies

screens/IntroSliders/backupRestoreIntro.tsx, screens/IntroSliders/biometricIntro.tsx, screens/IntroSliders/quickAccessIntro.tsx, screens/IntroSliders/secureShareIntro.tsx, screens/IntroSliders/trustedDigitalWalletIntro.tsx
> Added testId for intro-slider screens and refactor to improve readability
> [INJIMOB-2943](https://mosip.atlassian.net/browse/INJIMOB-2943&#41)
[INJIMOB-2943]: https://mosip.atlassian.net/browse/INJIMOB-2943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2943] add testId for intro-slider screens and refactor to improve readability

.talismanrc, android/app/build.gradle
[INJIMOB-2633](https://mosip.atlassian.net/browse/INJIMOB-2633)
[INJIMOB-2633]: https://mosip.atlassian.net/browse/INJIMOB-2633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2633]: [Develop]Add KMP artifact of Pixelpass 0.7.0, exclude dependencies in OVP library

shared/vcjs/verifyCredential.ts
[INJIMOB-2949](https://mosip.atlassian.net/browse/INJIMOB-2949)
[INJIMOB-2949]: https://mosip.atlassian.net/browse/INJIMOB-2949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2949]: [Develop]Fix for Mosip Vc Verrification while constructing Proof Purpose

android/app/build.gradle, android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
> update app version to 0.15.1 and update package.resolved
> [INJIMOB-3041](https://mosip.atlassian.net/browse/INJIMOB-3041&#41)
[INJIMOB-3041]: https://mosip.atlassian.net/browse/INJIMOB-3041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3041] update app version to 0.15.1 and update package.resolved

.github/workflows/ios-custom-build.yml
> add ios custom build workflow
> [INJIMOB-3041](https://mosip.atlassian.net/browse/INJIMOB-3041&#41)
[INJIMOB-3041]: https://mosip.atlassian.net/browse/INJIMOB-3041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3041] add ios custom build workflow

ios/fastlane/Fastfile
> fix path for ios artifact publish
> Example : [INJIMOB-3041](https://mosip.atlassian.net/browse/INJIMOB-3041&#41)
[INJIMOB-3041]: https://mosip.atlassian.net/browse/INJIMOB-3041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3041] fix path for ios artifact publish

components/VC/Views/VCCardViewContent.tsx
> Example : [INJIMOB-3108](https://mosip.atlassian.net/browse/INJIMOB-3108&#41)
[INJIMOB-3108]: https://mosip.atlassian.net/browse/INJIMOB-3108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3108]: Add test id for issuer logo in home screen card view

injitest/src/main/java/inji/pages/AddNewCardPage.java, injitest/src/main/java/inji/pages/MockCertifyLoginPage.java
INJIMOB-3107 fix the issuer selection for mdl in automation
=> INJIMOB-3107 fix the issuer selection for mdl in automation

android/app/build.gradle, android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj
[INJIMOB-3145](https://mosip.atlassian.net/browse/INJIMOB-3145)
[INJIMOB-3145]: https://mosip.atlassian.net/browse/INJIMOB-3145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3145]: Update to version 0.17.0.

.github/workflows/android-custom-build.yml, .github/workflows/push-triggers.yml, README.md
For "react-native" 0.74.x version, node version needs to be 18+ as per [docs](https://reactnative.dev/docs/0.74/set-up-your-environment#node--watchman)
> [INJIMOB-2381](https://mosip.atlassian.net/browse/INJIMOB-2381)
[INJIMOB-2381]: https://mosip.atlassian.net/browse/INJIMOB-2381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-2381] update node version in build workflows

components/VC/Views/VCCardView.tsx
Fix for undefined props in VcCardView
=> [INJIMOB-2452]: Fix for undefined props in VcCardView

components/VC/Views/VCCardView.tsx
> add null checks to fix crash issues in ios
> Example : [INJIMOB-3196](https://mosip.atlassian.net/browse/INJIMOB-3196&#41)
[INJIMOB-3196]: https://mosip.atlassian.net/browse/INJIMOB-3196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3196] add null checks to fix crash issues in ios

components/VC/common/VCItemField.tsx
- Fix for null values in Details screen
=> [INJIMOB-3188]: Fix for null values in Details screen

.talismanrc, machines/Issuers/IssuersMachine.ts, machines/Issuers/IssuersService.ts
Updating back to Auto Activation and keytype changes
=> [INJIMOB-3188]: Updating back to Auto Activation and keytype changes

.talismanrc, machines/Issuers/IssuersService.ts, shared/constants.ts
=> [INJIMOB-3188]: Defaulting RSA key type

components/VC/Views/VCDetailView.tsx
> remove face-placeholder from vc detail view
> Example : [INJIMOB-3069](https://mosip.atlassian.net/browse/INJIMOB-3069&#41)
[INJIMOB-3069]: https://mosip.atlassian.net/browse/INJIMOB-3069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3069] remove face-placeholder from vc detail view

.talismanrc, android/app/build.gradle, assets/Flip_Camera_Icon.svg, components/VC/Views/VCCardView.tsx, components/VC/common/VCUtils.tsx, components/kebabMenuUtils.ts, screens/Home/ViewVcModal.tsx, screens/Request/ReceiveVcScreen.tsx, shared/Utils.ts
[INJIMOB-3204](https://mosip.atlassian.net/browse/INJIMOB-3204)
Changes included:
- `Flip Camera’ icon theme is updated
- 'Share with selfie' option enabled for the VCs with face image
- Fix for Offline BLE sharing VC not getting rendered (until user connects back to the internet). When Internet is off, fields are updated with Title Case(for `firstName` , it will be displayed as `First Name`)
- Updated tuvali version to 0.5.2 as a fix for Android 14 and above QR sharing issue
[INJIMOB-3204]: https://mosip.atlassian.net/browse/INJIMOB-3204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3204]: Compass UI fixes

components/VC/common/VCUtils.tsx
Build failure due to Import redeclaration issue fixed
=> [INJIMOB-3204]: Import redeclaration issue fixed

components/QrScanner.tsx
> Example : [INJIMOB-3213](https://mosip.atlassian.net/browse/INJIMOB-3213&#41)
[INJIMOB-3213]: https://mosip.atlassian.net/browse/INJIMOB-3213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3213]: fix camera crash issue in scan screen

components/VC/Views/VCDetailView.tsx
> Example : [INJIMOB-3108](https://mosip.atlassian.net/browse/INJIMOB-3108&#41)
[INJIMOB-3108]: https://mosip.atlassian.net/browse/INJIMOB-3108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3108]: Add test id for issuer logo in VC details view screen

ios/Podfile, ios/fastlane/Fastfile
=> [INJIMOB-IOS-FIX]: Use Xcode 16 to build the ios apps

screens/Scan/SendVcScreen.tsx, screens/SplashScreen.tsx
-  Enable `Share with Selfie` in normal Share flow when VC has face image.
- Splash screen alignment
=> [INJIMOB-3188]: IOM demo feedbacks

ios/Podfile
> add post install hook to strip bitcodes from framework
> Example : [INJIMOB-3217](https://mosip.atlassian.net/browse/INJIMOB-3217&#41)
[INJIMOB-3217]: https://mosip.atlassian.net/browse/INJIMOB-3217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3217] add post install hook to strip bitcodes from framework

ios/Inji.xcodeproj/project.pbxproj
> Example : [INJIMOB-3222](https://mosip.atlassian.net/browse/INJIMOB-3222&#41)
[INJIMOB-3222]: https://mosip.atlassian.net/browse/INJIMOB-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3222]: Enable defines modules to generate headers

ios/Inji.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
> Example : [INJIMOB-3222](https://mosip.atlassian.net/browse/INJIMOB-3222&#41)
[INJIMOB-3222]: https://mosip.atlassian.net/browse/INJIMOB-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3222] - Remove modifying the product name based on flavour for header generation

ios/Inji.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
> Example : [INJIMOB-3222](https://mosip.atlassian.net/browse/INJIMOB-3222&#41)
[INJIMOB-3222]: https://mosip.atlassian.net/browse/INJIMOB-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3222] - Update output IPA name based on product name

.github/scripts/set-google-clientid.sh, .github/workflows/internal-build.yml, android/app/build.gradle, android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj, ios/fastlane/Fastfile
> Example : [INJIMOB-3188](https://mosip.atlassian.net/browse/INJIMOB-3188&#41)
[INJIMOB-3188]: https://mosip.atlassian.net/browse/INJIMOB-3188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3188]: update compass config for pipeline

machines/openID4VP/openID4VPServices.ts, package-lock.json, package.json, shared/cryptoutil/cryptoUtil.ts, shared/openId4VCI/Utils.ts
> Fixed ecr1 signature for ios, as previously it was jws specific.
>[INJIMOB-3015](https://mosip.atlassian.net/browse/INJIMOB-3015&#41)
[INJIMOB-3015]: https://mosip.atlassian.net/browse/INJIMOB-3015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3015] add noble ecr1 signature and remove jose signing for ios

screens/Settings/SettingScreen.tsx
- Remove backup and Restore from Settings Screen for Android
=> [INJIMOB-3188]: Remove backup and Restore from Settings Screen for Android

screens/Scan/SendVPScreenController.ts
=> [INJIMOB-fix]: Navigate to home screen with a delay for resettting error

components/VC/Views/VCDetailView.tsx, components/VC/common/VCUtils.tsx, screens/Home/ViewVcModal.tsx
>  remove display of keyType in VC detail view
=> [INJIMOB-2823] remove display of keyType in VC detail view

.github/workflows/android-custom-build.yml, android/fastlane/Fastfile
=> [INJIMOB-fix]: Fix compass apk name issue

android/app/build.gradle, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> use released version of tuvali instead of snapshot

ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
> update ios package dependencies for release 17
=> [INJIMOB-3244] update ios package dependency for release 17

injitest/src/test/java/BaseTest/BaseTest.java, injitest/src/test/java/androidTestCases/MosipOtpAlternativeFlow.java, injitest/src/test/java/androidTestCases/VcDownloadAndVerifyUsingMdl.java, injitest/src/test/java/iosTestCases/MosipOtpAlternativeFlow.java, injitest/src/test/java/iosTestCases/VcDownloadAndVerifyUsingMdl.java
MOSIP-41601 added soft assert for esignet error messages
=> MOSIP-41601 added soft assert for esignet error messages

injitest/src/main/java/inji/pages/AddNewCardPage.java, injitest/src/main/java/inji/pages/AppUnlockMethodPage.java, injitest/src/main/java/inji/pages/BackupDataTourPage.java, injitest/src/main/java/inji/pages/SunbirdLoginPage.java, injitest/src/main/java/inji/pages/WelcomePage.java, injitest/src/test/java/BaseTest/BaseTest.java, injitest/src/test/java/androidTestCases/MosipOtpAlternativeFlow.java, injitest/src/test/java/androidTestCases/VcDownloadAndVerifyUsingMdl.java, injitest/src/test/java/iosTestCases/MosipOtpAlternativeFlow.java, injitest/src/test/java/iosTestCases/VcDownloadAndVerifyUsingMdl.java
INJIMOB-2974 updated the description text for welcome page
=> INJIMOB-2974 updated the description text for welcome page

android/app/src/main/java/io/mosip/residentapp/InjiOpenID4VPModule.java, android/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/Podfile.lock, ios/RNOpenID4VPModule.m, ios/RNOpenID4VPModule.swift, machines/openID4VP/openID4VPServices.ts, package-lock.json, package.json, shared/Utils.ts, shared/cryptoutil/cryptoUtil.ts, shared/openID4VP/OpenID4VP.ts
release 0.17.0 sync to develop
=> [INJIMOB-3242]: Release 0.17.x sync to develop 

components/ui/Modal.tsx, injitest/src/main/java/inji/pages/HomePage.java
[INJIMOB-3301](https://mosip.atlassian.net/browse/INJIMOB-3301)
[INJIMOB-3301]: https://mosip.atlassian.net/browse/INJIMOB-3301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3301]: Fix for history page - close icon test id

components/CopilotTooltip.tsx, injitest/src/main/java/inji/pages/HomePage.java, injitest/src/test/java/androidTestCases/ChangeLanguageTest.java, injitest/src/test/java/androidTestCases/VerifyWelcomePagesTest.java, injitest/src/test/java/iosTestCases/ChangeLanguageTest.java, injitest/src/test/java/iosTestCases/VerifyWelcomePagesTest.java
[INJIMOB-3328](https://mosip.atlassian.net/browse/INJIMOB-3328)
[INJIMOB-3328]: https://mosip.atlassian.net/browse/INJIMOB-3328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3328]: Update testIDs for Tooltip buttons

components/VC/common/VCUtils.tsx
> add vc render fallback when credentialsubject is missing in wellknown
> [INJIMOB-3349](https://mosip.atlassian.net/browse/INJIMOB-3349&#41)
[INJIMOB-3349]: https://mosip.atlassian.net/browse/INJIMOB-3349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3349] add vc render fallback when credentialsubject is missing in wellknown

machines/openID4VP/openID4VPMachine.ts
> fix ios crash when vp sharing consent declined
> [INJIMOB-3370](https://mosip.atlassian.net/browse/INJIMOB-3370&#41)
[INJIMOB-3370]: https://mosip.atlassian.net/browse/INJIMOB-3370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3370] fix ios crash when vp sharing consent declined

.talismanrc, machines/Issuers/IssuersService.ts, machines/openID4VP/openID4VPActions.ts, machines/openID4VP/openID4VPServices.ts, screens/AuthWebViewScreen.tsx, screens/Scan/SendVPScreen.tsx, shared/openID4VP/OpenID4VP.ts, shared/openID4VP/OpenID4VPHelper.ts, shared/vciClient/VciClient.ts
* [INJIMOB-3389]: Implement Singleton pattern for Openid4vp Module
* [INJIMOB-3389]: Implement singleton pattern for VCI client module
* [INJIMOB-3389]: Update constructor for Openid4Vp singleton
[INJIMOB-3389]: https://mosip.atlassian.net/browse/INJIMOB-3389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-3389]: https://mosip.atlassian.net/browse/INJIMOB-3389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-3389]: https://mosip.atlassian.net/browse/INJIMOB-3389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3389]: Implement singleton pattern for OVP and VCI client Modules

.talismanrc, components/VC/common/VCUtils.tsx, machines/VerifiableCredential/VCItemMachine/VCItemSelectors.ts
* [INJIMOB-3381]: Check for different face fields and remove id during rendering
* [INJIMOB-3381]: Review comments addressed
* [INJIMOB-3381]: Face field null check updated
---------
[INJIMOB-3381]: https://mosip.atlassian.net/browse/INJIMOB-3381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-3381]: https://mosip.atlassian.net/browse/INJIMOB-3381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-3381]: https://mosip.atlassian.net/browse/INJIMOB-3381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> [INJIMOB-3381]: [Release]Check for different face fields and remove id during rendering

android/app/build.gradle, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
> update release 17 dependecies
> Example : [DSD-8574](https://mosip.atlassian.net/browse/INJIMOB-8574&#41)
[DSD-8574]: https://mosip.atlassian.net/browse/DSD-8574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DSD-8574] update release 17 dependecies

shared/VCMetadata.ts
This PR fixes 2 issues:
- backup flow not working - INJIMOB-3438
- No vc binded error msg even after having activated vc in wallet - INJIMOB-3440
=> [INJIMOB-3438]: update logic of credential id generation

android/app/build.gradle, android/fastlane/Fastfile, ios/Inji.xcodeproj/project.pbxproj, ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
>  update versions for 0.19.0 release
> [INJIMOB-3494](https://mosip.atlassian.net/browse/INJIMOB-3494&#41)
[INJIMOB-3494]: https://mosip.atlassian.net/browse/INJIMOB-3494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3494] update versions for 0.19.0 release

jest.config.js
> fix test config to ignore icon dependency. We added fontawesome icon sub-dependency
=> [INJIMOB-3494] fix test config to ignore icon dependency

android/app/build.gradle
Dependent PR - https://github.com/mosip/inji-openid4vp/pull/128
=> [INJIMOB-3490] fix: verification of JWS for OVP did scheme

docs/sdjwt-vp-support.md
[INJIMOB-3503](https://mosip.atlassian.net/browse/INJIMOB-3503)
[INJIMOB-3503]: https://mosip.atlassian.net/browse/INJIMOB-3503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3503] - Add doc for sd-jwt vp support

.eslintrc.js, .eslintrc.json, package-lock.json, package.json
[INJIMOB-3524](https://mosip.atlassian.net/browse/INJIMOB-3524)
[INJIMOB-3524]: https://mosip.atlassian.net/browse/INJIMOB-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INJIMOB-3524] - Remove eslint-plugin-sonarjs dependency
