mosip/inji-wallet

machines/openIdBle/scan.ts
package-lock.json
package.json

Includes the following
1. Implement cancel and disconnect functionality for IOS wallet (#547)
2. Dynamic MTU between IOS to Android and static MTU of 185 between Android to Android (#409)
3. Rename UUID characteristic names to the one used on spec (#444)
4. Remove un necessary bluetooth characteristics permissions and properties (#485)
5. Add logs for investigating Android GCM issue (#525)
Note: This release will be incompatible with earlier app versions. Both Wallet and Verifier should be updated to the current version to have the VC transfer to work.

IOS and Android VC transfer stability fixes

---

components/VcDetails.tsx
components/VcItem.tsx
locales/en.json
screens/Home/HomeScreen.tsx
screens/Home/ReceivedVcsTab.tsx
screens/Home/ViewVcModal.tsx
screens/Home/ViewVcModalController.ts
screens/Request/ReceiveVcScreen.tsx
screens/Scan/SendVcScreen.tsx

Changes in this build
* Change Send VC button labels - #589 
* Auto select first VC - #590 
* Remove Active button from receive VC's screen - #512

Feb 28th Release - Inji Changes

---

package-lock.json
package.json

**Enhancements as part of this release:**
- [iOS ]Disconnect connection when transfer is complete and verifier responds [mosip/inji/issues/593]
- [Android] Increase delay time during mtu exchange to 500ms  [mosip/inji/issues/566]
- [Android] Handle incomplete sequence numbers  [mosip/inji/issues/594]
- Remove all unnecessary logs  from android and change all print statements to OS_logs in iOS  [mosip/inji/issues/568]
- Refactor logTags to display className and versionTag of tuvali  [mosip/inji/issues/576]
- Display the selected VC while transferring the VC [mosip/inji/issues/590]
**Defects:**
- [iOS] Transfer Report writing with response and retry 3 times if it is not able to write  [mosip/inji/issues/567,  mosip/inji/issues/543]

Android & IOS stability Release build

---

package-lock.json
package.json

This fixes the compile time errors occurring in Inji due to Tuvali's npm executable scripts. These scripts were originally build for mac machine in the initial days when Inji app was not there. Now these Tuvali executable scripts aren't used.

chore(#696): Fix compile errors on windows machine due to Tuvali's incorrect build scripts for windows machine

---

machines/vcItem.ts

https://mosip.atlassian.net/browse/INJI-253
Issue - thumbprint was not set for custom library flow. As part of this PR, setting the thumbprint for custom secure keystore(Android) flow.

[INJI-253] Fix for Esignet login via kebab pop up VC activation

---

android/app/src/main/java/io/mosip/residentapp/MainActivity.java
android/build.gradle
package.json

* bump up react-native-gesture-handler version to 2.5.0
* remove RNGestureHandlerEnabledRootView as it is not needed in new version of react-native-gesture-handler

Update android target and compile sdk to API level 33

---

android/app/src/main/java/io/mosip/residentapp/MainActivity.java
android/build.gradle
package-lock.json
package.json

* bump up react-native-gesture-handler version to 2.5.0
* remove RNGestureHandlerEnabledRootView as it is not needed in new version of react-native-gesture-handler

update android target and compile sdk to API level 33($790)

---

screens/Home/MyVcs/HistoryTab.tsx

**[INJI-371](https://mosip.atlassian.net/browse/INJI-371)**  ->  The hash value of downloaded UIN/VID (downloaded vc) is shown on top of the "view activity log" screen in inji UI
[INJI-371]: https://mosip.atlassian.net/browse/INJI-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(INJI-371): View-activity-log-screen-header-resolved

---

screens/Home/HomeScreen.tsx
screens/Home/HomeScreenController.ts
screens/Home/HomeScreenMachine.ts
screens/Home/HomeScreenMachine.typegen.ts

When user clicks on plus icon in home page for downloading VC, if the device storage is less than the min threshold defined in our inji-default.properties file, error message overlay is shown (attached screenshot)
mosip.inji.minStorageRequired=5

feat(INJI-419): notify user on minStorageLimitReached while vc download

---

machines/issuersMachine.ts

remove conversion of json in downloaded credential response as request method called is already returning json type response. This eliminates error while vc download via eSignet

fix(INJI-205): vc download via esignet

---

components/ui/themes/DefaultTheme.ts
components/ui/themes/PurpleTheme.ts
screens/Home/IntroSlidersScreen.tsx
screens/SetupLanguageScreen.tsx

fix(INJI-260):refactor language setup and intro slider alignment in smaller display

---

machines/VCItemMachine/ExistingMosipVCItem/ExistingMosipVCItemMachine.ts
machines/vc.ts
screens/Home/MyVcsTab.tsx
screens/Home/MyVcsTabController.ts
shared/VCMetadata.ts

fix(INJI-536):check status failed while downloading vc

---

machines/bleShare/scan/scanMachine.typegen.ts
machines/settings.typegen.ts
shared/commonprops/commonProps.ts
shared/telemetry/TelemetryConstants.js

(Q) What we know so far?
(A) The crash is possible on Android & iOS if the Face SDK is not initialized, there could be other reasons as well hence we are going to log an event in Telemetry and observe if a crash still exists.
(Q) Have we verified that the app crashes?
(A) Yes, I have disabled the download of face model and tried to do a Share with Selfie and a Online QR Login on Android & iOS and in both platforms the phones have crashed.
(Q) Could there be other reasons for the crash?
(A) Yes, I’ve observed one of the issue and tried to fix it and I’ll be adding telemetry events to see if the crash still happens when the face SDK model is initialized correctly.

feat(INJI-622): add telemetry event to track face model init fail/sucess

---

screens/Home/MyVcs/AddVcModalController.ts
shared/GlobalVariables.ts

Changes include
1. fix - download cancel popup not shown when close icon is pressed in OTP modal while downloading VC
2. fix - Tuvali version not shown in About Inji page

fix: cancel download popup & tuvali version

---

screens/Home/ViewVcModal.tsx
screens/QrLogin/MyBindedVcs.tsx
screens/QrLogin/QrConsent.tsx
screens/QrLogin/QrLoginSuccessMessage.tsx
screens/Settings/ReceivedCardsModal.tsx
screens/Settings/SettingScreen.tsx
screens/VerifyIdentityOverlay.tsx

**[INJI-512](https://mosip.atlassian.net/browse/INJI-512)**:  
The navigation button to go back from the ID details page is missing, implemented as per wireframe provided.
**[Respective Screen Record](https://github.com/mosip/inji/assets/106086523/4d2a645f-76b7-4c2b-8983-182c6d3548d1)**
[INJI-512]: https://mosip.atlassian.net/browse/INJI-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INJI-512: The navigation button to go back from the ID details page provided as per wire frame.

---

.github/workflows/internal-build.yml
package.json

- gradlew sonar analysis file of kattu which we were using is performing the sonar qube analysis on the android native code but we wanted it to be applied on inji typescript files so using npm-sonar-analysis.yml file of kattu which is using sonar-scanner npm package

[Inji 597] use npm sonar-scanner package to perform sonar qube analysis on inji code

---

android/app/src/main/java/io/mosip/residentapp/MainActivity.java

App relaunchs when nearby permissions is allowed in scan screen and navigated to receive screen and vice versa. This was happening due to our custom logic handled in MainActivity onRequestPermissionsResult performing activity recreation when requestCode is  1 & is not denied. The requestCode for BLUETOOTH_SCAN (in Share screen) permission grant result is 1 (after giving nearby devices permission in receive screen) which satisfied the condition of app relaunch. For this reason onRequestPermissionsResult method has been removed.

[INJI-714] fix app relaunch in scan & receive screen

---

screens/Request/RequestLayout.tsx

**[INJIMOB-741](https://mosip.atlassian.net/browse/INJIMOB-741)**:  Android receive card header is fully in caps.
[INJIMOB-741]: https://mosip.atlassian.net/browse/INJIMOB-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INJIMOB-741: Fixed receive card header is fully in caps

---

.talismanrc
ios/Podfile.lock
machines/store.ts
package-lock.json
package.json
shared/cryptoutil/cryptoUtil.ts

When we pass data from a react native app with <part1>\x00<part2> value, any data post the \x00 gets truncated (i.e., part2 is trimmed off). This happens most likely with the react native bridge. To avoid this issue of truncation, we are required to pass the data as base64 encoded string and secure-keystore module will perform decoding before processing for encryption.
Pre-requisite: secure-keystore module needs to be updated to recent version before merging this PR

[INJIMOB-531] send base64 encode data to encrypt to avoid data truncation

---

machines/VCItemMachine/EsignetMosipVCItem/EsignetMosipVCItemMachine.ts
shared/VCMetadata.ts
shared/commonUtil.ts
shared/telemetry/TelemetryConstants.js
shared/vcjs/verifyCredential.ts

Mock the Verification of VC only for **RangeError** for MOSIP VC and **Sunbird VC**.
[INJIMOB-842](https://mosip.atlassian.net/browse/INJIMOB-842)
Druid : https://druid.obsrv.mosip.net/unified-console.html#workbench
Kafka : https://kafka.obsrv.mosip.net/ui/clusters/main_kafka/topics/mosip-telemetry/messages?q=VC%20verification&filterQueryType=STRING_CONTAINS&attempt=0&limit=100&seekDirection=FORWARD&seekType=OFFSET&seekTo=0::455549
Problem with druid in consuming the data from kafka to push in DB.
This Screen Shot Give us idea of how the data is pushed to kafka, when verification failed 
[INJIMOB-842]: https://mosip.atlassian.net/browse/INJIMOB-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-842]: mock the verification of vc only for range error for MOSIP VC.

---

machines/VerifiableCredential/VCItemMachine/VCItemServices.ts

Previously, while performing binding (VC activation) requesting OTP was sending individualId from credentialSubject(UIN) and validating OTP was sending individualId from VC metaData(VID) which caused mismatch and eventual binding failure. For resolving this, we are sending same individualId (id from VC metaData).

[INJIMOB-1188] fix binding failure of VCs downloaded via VID

---

ios/Inji-bridging-header.h
ios/Inji.xcodeproj/project.pbxproj

> The bridging header is required when swift is invoking a objC function.  Hence removing it
> Example : [INJIMOB-1313](https://mosip.atlassian.net/browse/INJIMOB-1313)
> 
[INJIMOB-1313]: https://mosip.atlassian.net/browse/INJIMOB-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

remove inji-briding-header.h file and build settings

---

injitest/androidRegression.xml
injitest/iosRegression.xml
injitest/src/main/java/inji/pages/SharePage.java
injitest/src/test/java/androidTestCases/ShareVcTest.java
injitest/src/test/java/iosTestCases/ShareVcTest.java

Automating the simulation of the camera disabled toaster error message on the share screen page on both IOS and android 
https://mosip.atlassian.net/browse/INJIMOB-1412

Automating the simulation of the camera disabled toaster error message

---

package-lock.json
package.json

> Revert tuvali version to 0.4.9
>  [INJIMOB-1411](https://mosip.atlassian.net/browse/INJIMOB-1411)
>
[INJIMOB-1411]: https://mosip.atlassian.net/browse/INJIMOB-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-1411]: revert tuvali version to 0.4.9

---

android/app/build.gradle
package-lock.json
package.json
shared/cryptoutil/cryptoUtil.ts

> Tuvali version is reverted back to 0.4.9
> Secure-keystore version is bumped up to 1.2.SNAPSHOT
> [INJIMOB-1387](https://mosip.atlassian.net/browse/INJIMOB-1387)
> [INJIMOB-890](https://mosip.atlassian.net/browse/INJIMOB-890)
[INJIMOB-1387]: https://mosip.atlassian.net/browse/INJIMOB-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-890]: https://mosip.atlassian.net/browse/INJIMOB-890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tuvali and SecureKeystore version change

---

machines/activityLog.ts
machines/activityLog.typegen.ts
machines/bleShare/scan/scanActions.ts
screens/Request/ReceiveVcScreen.tsx
screens/Request/ReceiveVcScreenController.ts

> During the VC share if wallet sends a VC of specific issuer to the verifier and there is no VC downloaded for that issuer on that device then default value will be shown as idType in the History screen so to avoid this and display correct idType we are storing wellknown config for received VC.
> Example : [INJIMOB-1192](https://mosip.atlassian.net/browse/INJIMOB-1192)
[INJIMOB-1192]: https://mosip.atlassian.net/browse/INJIMOB-1192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Injimob 1192] store wellknown config for received VC to display correct id type

---

android/app/src/main/java/io/mosip/residentapp/InjiVciClientModule.java
components/ActivityLogEvent.ts
components/VC/common/VCUtils.tsx
components/openId4VCI/CredentialType.tsx
machines/Issuers/IssuersActions.ts
machines/Issuers/IssuersService.ts
machines/QrLogin/QrLoginServices.ts
machines/VerifiableCredential/VCItemMachine/VCItemActions.ts
machines/VerifiableCredential/VCItemMachine/VCItemSelectors.ts
machines/VerifiableCredential/VCItemMachine/VCItemServices.ts
machines/bleShare/request/requestMachine.ts
machines/bleShare/scan/scanActions.ts
screens/Home/MyVcs/AddVcModalMachine.ts
screens/Home/MyVcs/HistoryTab.tsx
screens/Home/MyVcsTab.tsx
screens/Scan/SendVcScreenController.ts
shared/Utils.ts
shared/VCMetadata.ts
shared/api.ts
shared/openId4VCI/Utils.ts

> Fallback to config in case of wellknown  being unavailable for VCI flow
In case of
1. well-known availability
Credential_audience, Credential_endpoint, credentialFormat, credentialType, Scope is taken from the wellknown
2. well-known unavailability
We would be the taking the required info from config  (mimoto-issuers-config.json  in mosip-config repo)
Other changes
- Refactoring around identifier (id) of the VC metadata & id displayed (displayId) to user is made. 
More in detail, We have made changes in vcMetadata 
-> to take the id as credential Id of the VC (vc.credential.id - [ref](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-10.html#name-credential-issuer-metadata:~:text=%22id%22%3A%20%22http%3A//example.edu/credentials/3732%22%2C))
-> Introduced displayId …

[INJIMOB-1458] fallback issuers config if wellknown not available

---

shared/commonUtil.ts

> Since the size of the sunbird Vc is small and we are limiting the size to 2 decimal points the Data backed up was showing as 0.00 MB
(https://mosip.atlassian.net/browse/INJIMOB-1423))

[INJIMOB-1423]- Data Backedup size upto 3 decimal points

---

components/CopilotTooltip.tsx
components/ui/themes/DefaultTheme.ts
components/ui/themes/PurpleTheme.ts

> IOS - The buttons in the INJI tour guide are not properly aligned
>[INJIMOB-1503](https://mosip.atlassian.net/browse/INJIMOB-1503)
> ![image](https://github.com/mosip/inji/assets/97477121/683d7a9e-2d19-406b-acc8-245c2c35a1ec)
> ![image (5)](https://github.com/mosip/inji/assets/97477121/b21d4d3a-4a05-48a0-b646-6b6651344fc4)
>![image (4)](https://github.com/mosip/inji/assets/97477121/602149e1-e45a-4568-a7bd-5486da6a0b1f)
>![image (3)](https://github.com/mosip/inji/assets/97477121/a8e1be88-aee3-49de-a40a-4ca6f767e585)
>![image (2)](https://github.com/mosip/inji/assets/97477121/d9634cfe-0d8d-48a2-b189-425314de42de)
[INJIMOB-1503]: https://mosip.atlassian.net/browse/INJIMOB-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-1503]: fix tour guide buttons misalignment in IOS

---

android/app/build.gradle

> Update vci-client library version to 0.1.0-SNAPSHOT version to get latest library's changes including fix - attribute name mismatch on serialization process
>  [INJIMOB-1152](https://mosip.atlassian.net/browse/INJIMOB-1152&#41)
Response in INJI mobile's screenshot
>
[INJIMOB-1152]: https://mosip.atlassian.net/browse/INJIMOB-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-1552] update vci-client library version in android

---

components/VC/common/VCUtils.tsx

> Fixes background color not shown in VC as per configured in mimoto-issuers
> Example : [INJIMOB-2051](https://mosip.atlassian.net/browse/INJIMOB-2051&#41)
[> Add the Screenshots of the feature.](https://mosip.atlassian.net/browse/INJIMOB-2051?focusedCommentId=91766)
[INJIMOB-2051]: https://mosip.atlassian.net/browse/INJIMOB-2051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2051] fix Vc background not getting rendered

---

shared/api.ts
shared/openId4VCI/Utils.ts

> [INJIMOB-2073] change wellknown api from /.well-known to /well-known-proxy
> [INJIMOB-2073](https://mosip.atlassian.net/browse/INJIMOB-000&#41)
[INJIMOB-2073]: https://mosip.atlassian.net/browse/INJIMOB-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INJIMOB-2073]: https://mosip.atlassian.net/browse/INJIMOB-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2073] change wellknown api from /.well-known to /well-known-proxy

---

android/app/build.gradle

vcverifier-aar having the transitive dependency org.bouncycastle:bcpkix-jdk15on:1.69 was conflicting with the other  dependency's transitive depndencies of inji-wallet, to resolve this issue "org.bouncycastle:bcpkix-jdk15on:1.69" is excluded from vcverifier-aar

[INJIMOB-2260] exclude org.bouncycastle:bcpkix-jdk15on from vcverifier

---

components/EditableListItem.tsx
components/ui/themes/DefaultTheme.ts
components/ui/themes/PurpleTheme.ts
machines/settings.typegen.ts

> The alignment issue of the dialogue box during a error scenario has been fixed.
> Example : [INJIMOB-2241](https://mosip.atlassian.net/browse/INJIMOB-2241&#41)
[INJIMOB-2241]: https://mosip.atlassian.net/browse/INJIMOB-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2241] fix error text overlap on host selection overlay screen

---

android/app/src/main/java/io/mosip/residentapp/InjiOpenID4VPModule.java
ios/Inji.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/RNOpenID4VPModule.m
ios/RNOpenID4VPModule.swift
machines/openID4VP/openID4VPGuards.ts
machines/openID4VP/openID4VPMachine.ts
machines/openID4VP/openID4VPMachine.typegen.ts
machines/openID4VP/openID4VPServices.ts
shared/openID4VP/OpenID4VP.ts

> Wallet will fetch the openid4vp client validation property and pass it to the libraries and based on this value libraries will decide whether it should perform the client validation or not.
> Example : [INJIMOB-2538](https://mosip.atlassian.net/browse/INJIMOB-2538)
[INJIMOB-2538]: https://mosip.atlassian.net/browse/INJIMOB-2538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2538] fetch the openid4vp sharing flow client validation property from inji default properties file and pass it to library

---

.talismanrc
machines/Issuers/IssuersActions.ts
machines/VerifiableCredential/VCItemMachine/VCItemActions.ts
machines/VerifiableCredential/VCMetaMachine/vc.d.ts
package-lock.json
package.json
shared/Utils.ts
shared/VCMetadata.ts
shared/openId4VCI/Utils.ts

Previously, credential ID was used as a unique identifier of the VC in the wallet. But as per spec credential ID field is optional, to remove this dependency, Wallet will use a generated UUID  as the unique identifier for the VC. A UUID is generated on download which serves as identifier
`VC id = ${UUID}_${issuer}`
> [INJIMOB-2471](https://mosip.atlassian.net/browse/INJIMOB-2471)
[INJIMOB-2471]: https://mosip.atlassian.net/browse/INJIMOB-2471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Note: Tested VC download, Activation, QR login, backup / restore, share scenarios for sanity

[INJIMOB-2471] set UUID as vc identifier

---

machines/bleShare/scan/scanActions.ts

> Qr-login log was not showing up in vc activity log, vc key was not saved, which filtered out this log.
> [INJIMOB-2575](https://mosip.atlassian.net/browse/INJIMOB-2575)
[INJIMOB-2575]: https://mosip.atlassian.net/browse/INJIMOB-2575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2575] qr-login log in vc-activity log

---

.github/workflows/internal-build.yml
.github/workflows/ios-custom-build.yml
ios/fastlane/Fastfile

> modify ios/fastfile and internal build workflow to enable automation build without testflight deploy
> Example : [INJIMOB-2878](https://mosip.atlassian.net/browse/INJIMOB-2878&#41)
[INJIMOB-2878]: https://mosip.atlassian.net/browse/INJIMOB-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2878] modify ios/fastfile and internal build workflow to enable automation build without testflight deploy

---

.github/workflows/internal-build.yml
.github/workflows/ios-custom-build.yml

> remove enable auth user input for ios workflows
> Example : [INJIMOB-2779](https://mosip.atlassian.net/browse/INJIMOB-2779&#41)
[INJIMOB-2779]: https://mosip.atlassian.net/browse/INJIMOB-2779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2779] remove enable auth user input for ios workflows

---

machines/Issuers/IssuersService.ts
shared/openId4VCI/Utils.ts

> make authorization_servers optional and add fallback logic
> [INJIMOB-2985](https://mosip.atlassian.net/browse/INJIMOB-2985&#41)
[INJIMOB-2985]: https://mosip.atlassian.net/browse/INJIMOB-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-2985] make authorization_servers optional and add fallback logic

---

components/VC/common/VCUtils.tsx

> added fallback for missing display in credentialSubjectfields of wellknown to display in vc detail view.
> Example : [INJIMOB-3065](https://mosip.atlassian.net/browse/INJIMOB-3065&#41)
[INJIMOB-3065]: https://mosip.atlassian.net/browse/INJIMOB-3065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-3065] add fallback for missing display in credentialSubjectfields of wellknown

---

components/VC/common/VCUtils.tsx
components/openId4VCI/CredentialType.tsx

> if display property of credential type is missing we would fallback to `type` property for `name`.
> Example : [INJIMOB-3027](https://mosip.atlassian.net/browse/INJIMOB-3027&#41)
.
[INJIMOB-3027]: https://mosip.atlassian.net/browse/INJIMOB-3027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-3027] add fallback if display property of credential type is missing

---

machines/openID4VP/openID4VPModel.ts
screens/Scan/SendVPScreen.tsx
screens/Scan/SendVPScreenController.ts
shared/Utils.ts
shared/openID4VP/OpenID4VP.ts

For OVP flow, when sharing the VP a consent is shown to the user, if the client name is too long, it is trimmed and shown in the consent page
> [INJIMOB-3129](https://mosip.atlassian.net/browse/INJIMOB-3129&#41)
[INJIMOB-3129]: https://mosip.atlassian.net/browse/INJIMOB-3129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INJIMOB-3129] handle long client name consent

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/io/mosip/residentapp/InjiPackage.java
android/app/src/main/java/io/mosip/residentapp/IntentData.java
android/app/src/main/java/io/mosip/residentapp/MainActivity.java
android/app/src/main/java/io/mosip/residentapp/RNDeepLinkIntentModule.java
components/ui/Error.tsx
machines/app.ts
machines/bleShare/scan/scanActions.ts
machines/bleShare/scan/scanGuards.ts
machines/bleShare/scan/scanMachine.ts
machines/bleShare/scan/scanModel.ts
machines/bleShare/scan/scanSelectors.ts
machines/openID4VP/openID4VPActions.ts
machines/openID4VP/openID4VPMachine.ts
machines/openID4VP/openID4VPModel.ts
machines/openID4VP/openID4VPSelectors.ts
screens/MainLayout.tsx
screens/Scan/ScanLayout.tsx
screens/Scan/ScanLayoutController.ts
screens/Scan/ScanScreen.tsx
screens/Scan/ScanScreenController.ts
screens/Scan/SendVPScreen.tsx
screens/Scan/SendVPScreenController.ts
screens/Scan/SharingStatusModal.tsx
shared/Utils.ts
shared/constants.ts

Features added in Same device flow:
- Deeplink clicked from Browser/ Verifier in android.
- Through Intent Data, redirecting to Share screen of Wallet App installed inside the device.
- If matchingVCs are available, show list of matching VCs to share. After sharing the VC successfully, in success screen after 2 seconds delay, redirect back to Verifier.
- If user clicks on close icon or Reject button or declines the user consent, redirect back to Verifier.
- If no matchingVCs are available, show error screen and after 2 seconds delay, redirect back to Verifier.
- If no cards are available, show "No shareable cards available" screen and after 2 seconds delay, redirect back to Verifier.
- For all the above scenarios, Wallet should send success or error response when redirecting back to …

[INJIMOB-3154]:  Same device flow inOVP for Android

---

screens/IntroSliders/backupRestoreIntro.tsx
screens/IntroSliders/secureShareIntro.tsx

In the Introsliders when the user selects the preferred language as the tamil or kannada there was some alignment issues in the backup screen and sendvc screen

[INJIMOB-2977]:fix alignment issue in static screens of intro sliders

---

ios/fastlane/Fastfile

> change xcode version to 16.2 in ios/fastfile for new minimum required dependency of sdk ios 18.

[INJIMOB-0.16.x] select xcode16.2 for ios-app publish

---

.env
.talismanrc
screens/QrLogin/QrConsent.tsx
shared/constants.ts

- Captalize the field name. For eg: first_name will be displayed as First Name
- Maintaining `id` in acronym set in constants file for exception case to captialize to `ID`. So that, `national_id` will be displayed as `National ID`

[INJIMOB-3188]: QR consent claims display text updates

---

machines/Issuers/IssuersService.ts
machines/VerifiableCredential/VCItemMachine/VCItemServices.ts
shared/Utils.ts
shared/backupUtils/restoreData.ts
shared/openId4VCI/Utils.ts

The bypass that mock VCs had earlier to skip verification is removed and now the mock VCs are also verifiable by vc-verifier library

[INJIMOB-2299]: Enabling the mock VCs verification

---

.talismanrc
components/VC/Views/VCDetailView.tsx

- Currently only 1st element of the svg list is rendered in the assumption the certify supprots only 1 svg template.
- Updated the design , if any other issuer provides multiple renderMethod object, display the SVGs horizontally.

[INJIMOB-956]: Support SVG list in details screen
